pull_request_rules:
  - name: Develop to main fast-forward merge
    conditions:
      - or:
          - base=main
      - or:
          - head=develop
      - and:
          - -conflict
    actions:
      merge:
        method: fast-forward

  - name: Release squash merge
    conditions:
      - or:
          - base=main
      - or:
          - head~=^release-please--branches--main
      - and:
          - title~=^chore\(main\)
          - -conflict
    actions:
      merge:
        method: squash

  - name: Main to develop fast-forward merge
    conditions:
      - or:
          - base=develop
      - or:
          - head=main
      - and:
          - title=^resolve
          - -conflict
    actions:
      merge:
        method: fast-forward
