pull_request_rules:
  - name: Fast-forward merge
    conditions:
      - or:
          - base=develop
          - base=main
      - or:
          - head=develop
          - head=main
      - and:
          - -conflict
    actions:
      merge:
        method: fast-forward

  - name: Release squash merge
    conditions:
      - or:
          - base=main
      - or:
          - head~=^release-please--branches--main
      - and:
          - title~=^chore\(main\)
          - -conflict
    actions:
      merge:
        method: squash

  - name: main to develop fast-forward
    conditions:
      - or:
          - base=develop
      - or:
          - head=main
      - and:
          - title=^resolve
          - -conflict
    actions:
      merge:
        method: fast-forward
