site_name: "feature-reviser"
site_dir: public
docs_dir: ./docs
repo_url: https://github.com/chrislemke/feature-reviser
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: True
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.top
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra:
  generator: false
plugins:
  - search
  - autorefs
  - mkdocstrings

nav:
  - API reference:
      - Reviser: reviser-reference.md
      - Selector: selector-reference.md
      - Transformer:
          - Generic transformer: generic_transformer-reference.md
          - Encoder transformer: encoder_transformer-reference.md
          - Datetime transformer: datetime_transformer-reference.md
          - String transformer: string_transformer-reference.md
      - Utils: utils-reference.md
  - How to contribute: how_to_contribute.md
