name: BranchNameCheck
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  branch-name-check:
    if: ${{ !startsWith(github.head_ref, 'release-please--branches--main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          if: ${{ github.base_ref == 'main' && github.head_ref != 'develop' }}
          comment: |
            🚨 🚨 🚨
            Merging the `${{ github.head_ref }}` branch into `main` is not allowed.
            Only `develop` (and release branches) can be merged into `main`.

            **This pull request will be closed!**
