name: ChecksAndTesting

on:
  pull_request:
    branches: [develop]

jobs:
  analyze:
    name: Analyze code quality
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  python_testing:
    name: Python checks and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Python checks and tests
        run: |
          python --version
          rustc --version
          cargo tree
          python -m venv env
          source env/bin/activate
          pip install maturin
          maturin develop
          pip install "sk-transformers[dev, test]"
          black --check ./python/sk_transformers  ./tests/python
          mypy --config-file=pyproject.toml .
          bandit -r ./python/sk_transformers/*
          ruff ./python/sk_transformers ./tests/python
          pytest --cov tests/python --cov-fail-under=90 --cov-report term-missing

  rust_testing:
    name: Rust checks and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
      - name: Rust linting
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Rust testing
        run: |
          python -m venv env
          source env/bin/activate
          pip install maturin
          maturin develop
          pip install sk-transformers
          cargo build
          cargo check
          cargo test --all
