name: ChecksAndTesting

on:
  pull_request:
    branches: [develop]

jobs:
  analyze:
    name: Analyze code quality
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  testing:
    name: Checks and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and project
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install maturin
          maturin develop
          pip install "sk-transformers[dev]"

      - name: Check with black
        run: |
          black --check ./python/sk_transformers  ./tests/python
      - name: Check with mypy
        run: |
          mypy --config-file=pyproject.toml .
      - name: Check with bandit
        run: |
          bandit -r ./python/sk_transformers/*
      - name: Lint with ruff
        run: |
          ruff ./python/sk_transformers ./tests/python
      - name: Test with pytest
        run: |
          pytest --cov src/sk_transformers --cov-fail-under=90 --cov-report term-missing
