name: deploy_package
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install poetry==1.2.1
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_GITHUB_ACTIONS_TOKEN }}
      - run: poetry publish --build
